{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repaircafe.postgresSecretName" . }}
  labels:
    {{- include "repaircafe.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  database: {{ .Values.postgres.auth.database | quote }}
  databaseUrl: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "repaircafe.postgresHost" . }}:{{ .Values.postgres.service.port }}/{{ .Values.postgres.auth.database }}?schema=public"
{{- end }}
